language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install South
  - pip install django-tools
# command to run tests
script:
  - ./setup.py test
branches:
  only:
    - master
notifications:
  irc: "irc.freenode.org#pylucid"